-- STORED(오라클 서버의 캐시공간에 미리 저장된) PROCEDURE
-- UPDATE(쎄대여)
SELECT  PROD_ID, PROD_TOTALSTOCK
FROM    PROD
WHERE   PROD_ID = 'P101000001';
/
CREATE OR REPLACE PROCEDURE USP_PROD_TOTALSTOCK_UPDATE -- 실행이 아닌 컴파일되어 해시공간에 생성
IS
BEGIN
    UPDATE  PROD
    SET     PROD_TOTALSTOCK = PROD_TOTALSTOCK - 10
    WHERE   PROD_ID = 'P101000001';
    DBMS_OUTPUT.PUT_LINE('업데이트 성공');
    COMMIT;
END;
/
EXEC usp_prod_totalstock_update('P101000001');
/

SELECT  PROD_ID, PROD_TOTALSTOCK
FROM    PROD
WHERE   PROD_ID = 'P101000001';

CREATE OR REPLACE PROCEDURE USP_PROD_TOTALSTOCK_UPDATE -- 실행이 아닌 컴파일되어 해시공간에 생성
(P_PROD_ID IN VARCHAR2, P_PROD_TOTALSTOCK IN NUMBER)
IS
BEGIN
    UPDATE  PROD
    SET     PROD_TOTALSTOCK = PROD_TOTALSTOCK + P_PROD_TOTALSTOCK
    WHERE   PROD_ID = P_PROD_ID;
    DBMS_OUTPUT.PUT_LINE('업데이트 성공');
    COMMIT;
END;

EXEC usp_prod_totalstock_update('P201000002', 20);

SELECT  PROD_ID, PROD_NAME, PROD_TOTALSTOCK
FROM    PROD
WHERE   PROD_ID = 'P201000002';
/
SET SERVEROUTPUT ON;

-- 회원아이디를 입력받아 이름과 취미를 OUT 매개변수로 처리해보자
DECLARE
    --SCALAR변수
    V_NAME VARCHAR2(20);
    --REFERENCE변수
    V_LIKE member.mem_like%TYPE; -- =VARCHAR2(40)
BEGIN
    SELECT  MEM_NAME, MEM_LIKE INTO V_NAME, V_LIKE
    FROM    MEMBER
    WHERE   MEM_ID = 'a001';
    
    DBMS_OUTPUT.put_line(V_NAME||', '||V_LIKE);
END;
/
CREATE OR REPLACE PROCEDURE USP_GET_MEMBER
(P_MEM_ID IN VARCHAR2,P_MEM_NAME OUT VARCHAR2, P_MEM_LIKE OUT VERCHAR2)
IS
    --SCALAR변수
    V_NAME VARCHAR2(20);
    --REFERENCE변수
    V_LIKE member.mem_like%TYPE; -- =VARCHAR2(40)
BEGIN
    SELECT  MEM_NAME, MEM_LIKE INTO V_NAME, V_LIKE
    FROM    MEMBER
    WHERE   MEM_ID = P_MEM_ID;
    
    DBMS_OUTPUT.put_line(V_NAME||', '||V_LIKE);
END;
/
VAR MEM_NAME VARCHAR2(20)
VAR MEM_LIKE VARCHAR2(20)
EXEC USP_GET_MEMBER('c001', :MEM_NAME, :MEM_LIKE);
PRINT MEM_NAME
PRINT MEM_LIKE;

--회원별
--구매금액의 합:SUM(PROD_SALE * CART_QTY
--을 구하는 쿼리를 만들어보자
--이중에서 구매금액의 합이 가장 많은 1명만 출력해보자
-- Alias: MEM_NAME, MEM_AMT

CREATE OR REPLACE PROCEDURE USP_MEM_TOP
(P_YEAR IN VARCHAR2, P_MEM_NAME OUT VARCHAR2, P_MEM_AMT OUT NUMBER)
IS
BEGIN
    SELECT TA.MEM_NAME, TA.MEM_AMT INTO P_MEM_NAME, P_MEM_AMT
    FROM   (SELECT     A.MEM_NAME, SUM(B.PROD_SALE * C.CART_QTY) AS MEM_AMT
            FROM       MEMBER A
            INNER JOIN CART C ON(A.MEM_ID=C.CART_MEMBER)
            INNER JOIN PROD B ON(B.PROD_ID=C.CART_PROD)
            where      cart_no like P_YEAR || '%'
            GROUP BY   A.MEM_NAME
            ORDER BY   2 DESC) TA
    WHERE  ROWNUM <= 1;
END;
/

VAR P_MEM_NAME VARCHAR2
VAR P_MEM_AMT  NUMBER
EXEC USP_MEM_TOP('2020', :P_MEM_NAME, :P_MEM_AMT)
PRINT P_MEM_NAME
PRINT P_MEM_AMT;
/

-- 상품코드와 월을 입력하면 해당 월에 대한 해당 상품의 입고, 출고를 처리해 화면에 출력해보자
-- (프로시저명 : USP_PROD_INFO, 월 형식은 YYYYMM이라 가정, 입고 및 출고는 OUT 매개변수로 처리)

    SELECT      BUY_PROD 상품번호,
                SUBSTR(CART_NO,1,6) 판매일자,
                TO_CHAR(B.BUY_DATE, 'YYYYMM') 매입일자,
                SUM(BUY_QTY) BSUM,
                SUM(CART_QTY) CSUM
    FROM        PROD P
    INNER JOIN  BUYPROD B ON(P.PROD_ID=B.BUY_PROD AND SUBSTR(TO_CHAR(B.BUY_DATE, 'YYYYMM'),5,2)='04')
    INNER JOIN  CART C ON(P.PROD_ID=C.CART_PROD AND SUBSTR(CART_NO,5,2)='04')
    WHERE       PROD_ID = 'P101000001'
    GROUP BY    BUY_PROD, CART_NO, BUY_DATE
    ORDER BY    1;
/

CREATE OR REPLACE VIEW VM_MONTHS_IN_OUT (WOL,IN_AMT,OUT_AMT) AS 
    
    SELECT H.WOL 월, NVL(I.IN_AMT,0) 입고, NVL(J.OUT_AMT,0) 출고
    FROM
    (
        SELECT LEVEL WOL
         FROM DUAL
         CONNECT BY LEVEL +1 <=13
    ) H,
    (
        SELECT EXTRACT(MONTH FROM BUY_DATE) WOL, SUM(BUY_QTY) IN_AMT
        FROM  PROD, BUYPROD
        WHERE PROD_ID=BUY_PROD
        AND   TO_CHAR(BUY_DATE,'YYYY') = '2020'
        GROUP BY  EXTRACT(MONTH FROM BUY_DATE)
    ) I,
    (
        SELECT TO_NUMBER(SUBSTR(CART_NO,5,2))WOL, SUM(CART_QTY) OUT_AMT
        FROM  CART C
        WHERE PROD_ID=CART_PROD
        AND   CART_NO LIKE '2020%'
        GROUP BY TO_NUMBER(SUBSTR(CART_NO,5,2))
    ) J
    WHERE H.WOL = I.WOL(+)
    AND H.WOL = J.WOL(+)
    ORDER BY 1;
/
SELECT LEVEL FROM DUAL
CONNECT BY LEVEL<=10;
/
SELECT TO_DATE('20220501','YYYYMMDD') + (ROWNUM-1) AS CAL
FROM DUAL
CONNECT BY LEVEL <= (TO_DATE('20220531','YYYYMMDD')
             -TO_DATE('20220501','YYYYMMDD')+1);
/ -- 학사관리 시스템 및 시간표에 많이 적용됨.