-- STORED(오라클 서버의 캐시공간에 미리 저장된) PROCEDURE
-- UPDATE(쎄대여)
SELECT  PROD_ID, PROD_TOTALSTOCK
FROM    PROD
WHERE   PROD_ID = 'P101000001';
/
CREATE OR REPLACE PROCEDURE USP_PROD_TOTALSTOCK_UPDATE -- 실행이 아닌 컴파일되어 해시공간에 생성
IS
BEGIN
    UPDATE  PROD
    SET     PROD_TOTALSTOCK = PROD_TOTALSTOCK - 10
    WHERE   PROD_ID = 'P101000001';
    DBMS_OUTPUT.PUT_LINE('업데이트 성공');
    COMMIT;
END;
/
EXEC usp_prod_totalstock_update;