--------------------------------------------------------
--  파일이 생성됨 - 목요일-4월-21-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEPTS
--------------------------------------------------------

  CREATE TABLE DEPTS ("DEPARTMENT_ID" NUMBER(4,0), "DEPARTMENT_NAME" VARCHAR2(30), "MANAGER_ID" NUMBER(6,0), "LOCATION_ID" NUMBER(4,0), "PARENT_ID" NUMBER(4,0));
REM INSERTING into HR.DEPTS
SET DEFINE OFF;
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (10,'총무기획부',200,1700,null);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (20,'마케팅',201,1800,10);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (30,'구매/생산부',114,1700,10);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (40,'인사부',203,2400,10);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (50,'배송부',121,1500,10);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (60,'IT',103,1400,90);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (70,'홍보부',204,2700,90);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (80,'영업부',145,2500,10);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (90,'기획부',100,1700,10);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (100,'자금부',108,1700,90);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (110,'경리부',205,1700,90);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (120,'재무팀',null,1700,110);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (130,'세무팀',null,1700,100);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (140,'신용관리팀',null,1700,100);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (150,'주식관리팀',null,1700,100);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (160,'수익관리팀',null,1700,100);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (170,'생산팀',null,1700,30);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (180,'건설팀',null,1700,30);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (190,'계약팀',null,1700,80);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (200,'운영팀',null,1700,30);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (210,'IT 지원',null,1700,30);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (220,'NOC',null,1700,30);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (230,'IT 헬프데스크',null,1700,60);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (240,'공공 판매사업팀',null,1700,80);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (250,'판매팀',null,1700,80);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (260,'채용팀',null,1700,40);
Insert into HR.DEPTS (DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID,PARENT_ID) values (270,'급여팀',null,1700,110);
